#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "Running lint-staged"
npm run lintStaged
echo "Running tsc"
npm run listErrors
echo "Running unit tests"
npm run test:unit
echo "Running db tests"
npm run test:db
echo "Running e2e tests"
npm run test:e2e
